### ISSUE TITLE
Elaboration on Known limitation in BAMOE 9.x release notes for stateful process support & usage. 

### ISSUE THREAD

**Issue by ksamir18sk** [IBM/bamoe-docs#102]
In the release notes for 9.0.0 and 9.0.1:

9.0.0 release note has this section: https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=notes-bamoe-release-version-900

```
Unsupported capabilities on 9.0
-Stateful Processes

```

This needs to be more elaborative.

======================

9.0.1 release note has a 'Known limitation section' section: https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=notes-bamoe-release-version-901
```
 Known limitations
-To review the most current known limitations in detail, see Known limitations in IBM Business Automation Manager Open Editions 9.0.1 fix releases. The issues that arise will be reported through this source.
```
But in this known limitation, it doesn't mention it although stateful processes have not been released yet. Therefore it needs to be clearer in this as well.

======================

This limitation/unsupported capability should be documented in all the upcoming release notes until it is released.

We can add something as below:

**Stateful Processes: Please note that as of BAMOE version 9.0.x, only decisions are supported, and stateful process use cases are not yet supported (BPMN files can be used - but only STP focused on rules orchestration). This means that workflows and stateful processes may not function as expected in your current 9.x environment if you try using a community approach in your current implementation/design phase.**

**Comment by veena-ux** [comment]
@ksamir18sk - We will update this later in 9.0 version.

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146274
