### ISSUE TITLE
Wrong product version attribute in RHPAM 7 to BAMOE 8 migration document.

### ISSUE THREAD

**Issue by ksamir18sk** [IBM/bamoe-docs#105]
In the following doc - https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=guide-red-hat-v7-bamoe-v8

Under 'Common Product Archives' table, the **bamoe-installer-{VERSION}.jar** description mentions product version as 9.0.1, the attribute should instead be 8.0.3 as per the product archives version in the screenshot in the link .

<img width="1383" alt="Screenshot 2024-05-02 at 08 31 37" src="https://github.com/IBM/bamoe-docs/assets/150439767/2e1e79f4-81de-41be-9d45-2190da49672b">

**Comment by veena-ux** [comment]
@ksamir18sk - It is fixed in 9.1.0. This will be updated in 9.0.1 after the current release. Thanks.
