### ISSUE TITLE
Placeholder not replaced with actual Maven link in the RHPAM 7 to BAMOE 8 document for migration.

### ISSUE THREAD

**Issue by ksamir18sk** [IBM/bamoe-docs#106]
In the RHPAM 7 to BAMOE 8 migration doc - https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=guide-red-hat-v7-bamoe-v8

There looks to be a typo in the following sections:

_Step 2: Update Maven Configuration
MAVEN_SITE_URL_BASE}[Apache Maven] is a software project management and comprehension tool. Based on the concept of a project object model (POM), Maven can manage a project’s build, reporting and documentation from a central piece of information. IBM Business Automation Manager Open Editions relies on Maven in order to build various types of deployable artifacts, such as decision service applications. For a quick start see the [Maven Quick Start Guide](https://www.ibm.com/links?url=http%3A%2F%2Fmaven.apache.org%2Fguides%2Fgetting-started%2F)._

The **_MAVEN_SITE_URL_BASE}_** looks to be a placeholder which likely was intended to be replaced with the actual URL base for Maven's documentation or website. But for some reason placeholder was not properly replaced with the actual URL.

**Comment by veena-ux** [comment]
@ksamir18sk - This is fixed in 9.1.0. We will revisit what we do to fix 9.0.1 after the current release. Thanks.

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146276
