### ISSUE TITLE
Fixes needed in 9.0.1 documentation, in the "7 to 8 migration" tab

### ISSUE THREAD

**Issue by rbourner** [IBM/bamoe-docs#125]
- It reads "The following tools are required in order to migrate to BAMOE v9.0.0", but this section is not about version 9.
- The table #2 detailing the versions mapping is missing the latest 8 version i.e. 8.0.5.   This seems fixed in the 9.1.0 documentation (ibmdoc-test).
- Why is table #2 duplicated in table [#3](https://ibm-cloud.slack.com/archives/C03JW9K175Z)? 
- In Step 3 "Update Tooling & Runtime", the Smart Router is missing in the list of components. If nothing needs to be done as part of the 7 to 8 migration, it should say it.
- In the "Procedure" paragraph, Step 6, typo: "IIBM" instead of "IBM"
- In the "Procedure" paragraph, Step 6, it mentions an older 8.0.3 version. It should either say 8.0.5 or 8.0.x.
- In the "Procedure" paragraph, Step 8, it says "Start IBM BAMOE and KIE Server" where it should read "Start Business/Decision Central and KIE Server"
- In the "Step 3: Update Persistence" paragraph, in the Note section, typo: "migraet" instead of "migrate"
- I would think there should also be a section for clients using RHPAM/BAMOE in a SpringBoot context and what they need to do as part of their migration vs. what is currently listed in a JBoss deployment context.
- In the "Update to use the Maven Bill of Materials (BOM)" section, typo: "depenency" should read "dependency"

**Comment by rbourner** [comment]
Wrong references in the comment above: no link to docker doc should have been added, this was caused by the # sign.

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146278
