### ISSUE TITLE
Incorrect version mention for patch upgrade in BAMOE 9.0.1 release note.

### ISSUE THREAD

**Issue by ksamir18sk** [IBM/bamoe-docs#135]
Problem Description:

In the release notes of 9.0.1 - https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=notes-bamoe-release-version-901

Under **New in this release**, the following point is mentioned incorrectly- 

_Documented instructions for patch update from 9.0.1 to 9.0.1_

Improvement Proposal:
Expected sentence should be as follows- _Documented instructions for patch update from 9.0.0 to 9.0.1_

Problem found: 
https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=notes-bamoe-release-version-901

Support cases and customers affected: - 

Technical contacts: Nikolai K.

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146279
