### ISSUE TITLE
Incorrect version identifier for BAMOE 8.0.5 (0007 instead of 00017)

### ISSUE THREAD

**Issue by ksamir18sk** [IBM/bamoe-docs#144]
Problem Description:
Incorrect jar file path mentioned below in the procedure of BAMOE v8 document hosted by RH-

https://access.redhat.com/documentation/en-us/ibm_business_automation_manager_open_editions/8.0/html-single/integrating_ibm_business_automation_manager_open_editions_with_other_products_and_components/index#kieserver-kafka-emit-proc_integrating-amq-streams

**Procedure**

_To send Kafka messages automatically, complete one of the following tasks:

- If you deployed KIE Server on Red Hat JBoss EAP or another application server, complete the following steps:

> 1. Download the bamoe-8.0.5-maven-repository.zip product deliverable file from the [Software Downloads](https://www.ibm.com/support/pages/node/6596913) page of the Red Hat Customer Portal.
> 2. Extract the contents of the file.
> **3. Copy the maven-repository/org/jbpm/jbpm-event-emitters-kafka/7.67.2.Final-redhat-0007/jbpm-event-emitters-kafka-7.67.2.Final-redhat-0007.jar file into the deployments/kie-server.war/WEB-INF/lib subdirectory of the application server.**
>_ 

Improvement Proposal:
There is no 7.67.2.Final-redhat-0007 associated to any BAMOE version.
Rather it should be 7.67.2.Final-redhat-0017 (If we are trying to frame the procedure in this document as per 8.0.5 version)

Problem found:
https://access.redhat.com/documentation/en-us/ibm_business_automation_manager_open_editions/8.0/html-single/integrating_ibm_business_automation_manager_open_editions_with_other_products_and_components/index#kieserver-kafka-emit-proc_integrating-amq-streams

Support cases and customers affected: TS016313577

Technical contacts: -

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146280
