### ISSUE TITLE
Clarity on BAMOE migration directly from v7 to v9

### ISSUE THREAD

**Issue by ksamir18sk** [IBM/bamoe-docs#56]
The migration guidelines of BAMOE, https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=migration-guide provides information to migrate from v6 > v7, v7 > v8 and v8 > v9. Customers are enquiring about direct migration from v7 to v9.

From recent discussion in the release call, 7 > 8 and then 8 > 9 is the recommended migration path and should be followed by the customer. The documentation however does not state it clearly.

According to discussion with Documentation team, there is an appropriate statement available, formulated in a way that would clarify the doubts. The statement should be added to the official migration guidelines.

**Comment by blulas** [comment]
I will make this address this as part of my minor update today.

**Comment by samiya-kashif** [comment]
As per discussion with Documentation team during release call, Justine Mills mentioned that there already exists such a statement somewhere, which she can find and update the documentation.

**Comment by kmacedovarela** [comment]
There is no documentation for direct migration from 7 to 9 as discussed during calls. This should be done by professional services and can be addressed by a tech note of type question.

**Comment by kmacedovarela** [comment]
PRs are also welcome

**Comment by justlmills** [comment]
I propose to integrate the following statement under the Overview heading in this page : https://ibmdocs-test.dcs.ibm.com/docs/en/ibamoe/9.0.x?topic=migration-guide

"This section describes how to migrate your existing business automation applications and platforms to most recent version of IBM Business Automation Manager Open Editions. The supported upgrade process is from the previous version to the current version.  If you are migrating from an older version you must follow the migration steps to upgrade to each of the intermediate versions, as documented. Depending on the complexity of your installation, you might want IBM® Services to participate in your project. If so, contact your IBM service representative."

**Comment by samiya-kashif** [comment]
This is reasonable and clear.

**Comment by blulas** [comment]
I've added that exact statement to the overview section, included in my upcoming PR

**Comment by LightGuard** [comment]
Was this closed with #67 ?

**Comment by LightGuard** [comment]
Closing this on Monday if there's no update.
