### ISSUE TITLE
Documentation version

### ISSUE THREAD

**Issue by kmacedovarela** [IBM/bamoe-docs#58]
We proper versioning for the documentation and that should be visible on the webpage, throughout al sections. We need it to be able to use as reference as we move forward and start having more frequent releases of it.

**Comment by kmacedovarela** [comment]
@veena-ux

**Comment by LightGuard** [comment]
I am not sure what the request is here. We have the version in three different places on every page:
* The search bar at the top
* The dropdown menu on the left
* The breadcrumb at the top of every page.

**Comment by LightGuard** [comment]
Closing this on Monday if there's no update.
