### ISSUE TITLE
Document integration of Kafka with the BPM engine

### ISSUE THREAD

**Issue by naval-suvarna** [IBM/bamoe-docs#84]
Client is exploring the intgration of kafka with the BPM engine,Product Version : 8.0.0 they are trying sending messages to start, intermediates and end events messages, and everything is working well.
The problem comes when they have more than one process instance and they want to notify only one. It should be possible to trigger only specific instances using correlation properties, but this is not documented.
I found a link regarding the kafka integration but not sure how to do it.
https://github.com/kiegroup/jbpm/blob/main/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/SendSignalAction.java#L59-L72

**Comment by LightGuard** [comment]
@naval-suvarna Perhaps https://access.redhat.com/documentation/en-us/ibm_business_automation_manager_open_editions/8.0/html-single/integrating_ibm_business_automation_manager_open_editions_with_other_products_and_components/index#assembly-integrating-amq-streams may be of some help or guidance.

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146270
