### ISSUE TITLE
Examples in the 15-minute series link to old KIE repo and are 404ing

### ISSUE THREAD

**Issue by timwuthenow** [IBM/bamoe-docs#88]
When doing the 15-minute examples, several are 404-ing with the move to the Apache-incubator repository. This can be seen in https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=started-orchestrating-decisions-rules-in-15-minutes which points to https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-business-rules-quarkus but this will return a 404 on the particular identified project. This should be at https://github.com/apache/incubator-kie-kogito-examples/tree/stable/kogito-quarkus-examples/process-business-rules-quarkus

The linked project should probably also be to a particular branch that uses the IBM build of Kogito for said example versus the stable branch using most current.

**Comment by rodrigonull** [comment]
Issue migrated to JIRA: https://jsw.ibm.com/browse/DBACLD-146271
